"""
Django settings for Hidrina_Website project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import django

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dd(fojpxjpq)_(n#sbmgi$n0q0ewx1v=0j=lcl9%g7o6cx@oyn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["hidrinasponsorship.com", "https://hidrinasponsorship.com", "www.hidrinasponsorship.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'User_App',
    'Auth_App',
    'Sponsor_App',
    'Super_Admin_App',
    'Messaging',
    'captcha',
    'stripe',
    'django_countries',
    'paypal.standard.ipn',
]

CAPTCHA_FONT_SIZE = 40
CAPTCHA_IMAGE_SIZE = (150, 50)
CAPTCHA_FOREGROUND_COLOR = '#001F3F'
CAPTCHA_BACKGROUND_COLOR = '#FFFFFF'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Hidrina_Website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hidrina_Website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # URL to access static files
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.hidrinasponsorship.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = "hidrina@hidrinasponsorship.com"
EMAIL_HOST_PASSWORD = "hidrinasponsorship"
EMAIL_USE_SSL = True

STRIPE_PUBLISHABLE_KEY = "pk_test_51MesyURrwQfTWptQiWgSRQNztyLlr0pnM0duElooidTFonJNz6GBg9sV9pe1JkudWCzjZl1YrbFuo7xj7VpfGBQV00FYBavB6B"
STRIPE_SECRET_KEY = "sk_test_51MesyURrwQfTWptQ4xBQh3VVU59pLrqI6PLFpYfLbio7OX6WYIpsu9aqF3L91ilG2EzDeO9wdKcdP7zplWqyG5Jx00rloWK0S1"
STRIPE_WEBHOOK_SECRET = "whsec_4nz4DAIYfdO5P47UMMLomY2Hnp0z5iGa"

PAYPAL_CLIENT_ID = "ARDwgsy_tNRfW2inVJ-bBD5BsppiEY3-t0vpuHDWISdMFbEyaLlhee2R_oBdK_xai5oDL3oWCqf9kiHL"
PAYPAL_SECRET_KEY = "EC28vsKv6XKLQte7u5P5qpgHz8CFgyDqnp1R2gbz7SP5A0P9omh9a3GlyWq3jWBG6m4wt5r9pZ5DOooz"
PAYPAL_MODE = "sandbox"
PAYPAL_TEST = True
PAYPAL_RECEIVER_EMAIL = "eminemmerne@gmail.com"