# Generated by Django 5.1.1 on 2024-09-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_address', models.CharField(max_length=100)),
                ('no_of_family_members', models.PositiveIntegerField()),
                ('family_bio', models.TextField()),
                ('is_sponsored', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='family_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
