# Generated by Django 5.1.1 on 2024-09-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0002_alter_sponsoredfamily_options_administrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Adminstrators'},
        ),
    ]
