# Generated by Django 5.1.1 on 2024-09-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0004_remove_sponsoredfamily_photo_familyimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SponsoredFamily',
            new_name='FamilyList',
        ),
    ]
