# Generated by Django 5.1.1 on 2024-09-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0005_rename_sponsoredfamily_familylist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familylist',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Families List'},
        ),
    ]
