# Generated by Django 5.1.1 on 2024-09-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0008_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familylist',
            name='family_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
