# Generated by Django 5.1.1 on 2024-09-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0009_alter_familylist_family_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familylist',
            name='contact_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familylist',
            name='family_bio',
            field=models.TextField(),
        ),
    ]
