# Generated by Django 5.1.1 on 2024-09-23 08:29

import Super_Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0010_alter_familylist_contact_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyimage',
            name='photo',
            field=models.ImageField(upload_to='family_photos/', validators=[Super_Admin_App.models.validate_image]),
        ),
    ]
