# Generated by Django 5.1.1 on 2024-10-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0016_payment_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylist',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
