# Generated by Django 5.1.1 on 2024-12-07 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0017_familylist_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='overdue_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 6, 47, 51, 30592, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
