# Generated by Django 5.1.1 on 2024-12-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0019_alter_payment_overdue_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='overdue_payment',
            field=models.DateTimeField(),
        ),
    ]
