# Generated by Django 5.1.1 on 2024-12-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0020_alter_payment_overdue_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familylist',
            name='no_of_family_members',
        ),
    ]
