# Generated by Django 5.1.1 on 2024-12-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0021_remove_familylist_no_of_family_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyListTig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact_address', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=255, null=True)),
                ('family_bio', models.TextField()),
                ('is_sponsored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_list_tig', to='Super_Admin_App.familylist')),
            ],
            options={
                'verbose_name_plural': 'Families List',
                'ordering': ['-created_at'],
            },
        ),
    ]
