# Generated by Django 5.1.1 on 2024-12-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0022_familylisttig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyListTig',
        ),
    ]
