# Generated by Django 5.1.1 on 2025-02-16 11:45

import Super_Admin_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0024_emailcredential_alter_monthlyamount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylist',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familyimage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='family_photos/', validators=[Super_Admin_App.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='familylist',
            name='family_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
