# Generated by Django 5.1.1 on 2025-02-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0025_familylist_gender_alter_familyimage_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCredential',
        ),
    ]
