# Generated by Django 5.1.1 on 2025-02-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Super_Admin_App', '0026_delete_emailcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='admin_photo',
            field=models.ImageField(blank=True, upload_to='admin_media'),
        ),
    ]
