# Generated by Django 5.1.1 on 2024-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='hey', max_length=255),
            preserve_default=False,
        ),
    ]
