# Generated by Django 5.1.1 on 2024-10-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor_App', '0002_sponosraccount_admin_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponosraccount',
            old_name='admin_photo',
            new_name='sponsor_photo',
        ),
    ]
