# Generated by Django 5.1.1 on 2024-10-17 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor_App', '0005_sponsorfamilyrelation'),
        ('Super_Admin_App', '0016_payment_is_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sponsorfamilyrelation',
            unique_together={('sponsor', 'family')},
        ),
    ]
