# Generated by Django 5.1.1 on 2024-10-18 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor_App', '0006_alter_sponsorfamilyrelation_unique_together'),
        ('Super_Admin_App', '0016_payment_is_seen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sponsorfamilyrelation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sponsorfamilyrelation',
            name='family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='Super_Admin_App.familylist'),
        ),
    ]
