# Generated by Django 5.1.1 on 2024-10-18 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsor_App', '0007_alter_sponsorfamilyrelation_unique_together_and_more'),
        ('Super_Admin_App', '0016_payment_is_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorfamilyrelation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='Super_Admin_App.familylist'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorfamilyrelation',
            unique_together={('sponsor', 'family')},
        ),
    ]
